### ISSUE TITLE
How to use python script inside the docker

### ISSUE THREAD

**Issue by Ailurupoda** [mundialis/grass-py3-pdal#7]
Hi,
I'm using the docker to run bash files and it's very powerful.
I would like to know if it is possible to also run python script with this docker and how it would be possible ?

I saw that inside the docker there is a python script, but i didn't understood how to run it like i run the bash script and did not manage to run my own python script.

Thanks for your help,

**Comment by neteler** [comment]
Good point! I have added a new section to the README.md file:

## Using Python

Thee script below uses the Python API of GRASS GIS to make use of functionality without
explicitely starting an interactive GRASS GIS session. Moreover, we use the
`grass-session` Python interface here.

In this example, we import of the "admin0" level vector data from
[Natural Earth](https://www.naturalearthdata.com/). The Python script downloads and imports
the vector data including a topological cleaning on the fly.

```bash
# download sample script
wget https://neteler.gitlab.io/grass-gis-analysis/grass_session_vector_import.py
# run it (we explicitely define the GRASS GIS start script name here)
export GRASSBIN=grass ; python3 grass_session_vector_import.py
```

Hope it helps - if not, let us know.
